name: webhook_proxy
version: 0.0.1
description: >
    proxy for github's webhook that supports
    issue title and description update events
author: Boris <akiroz.vectis@gmail.com>
homepage: https://github.com/akiroz/webhook-proxy
dependencies:
    test:   '^0.12.11+2'
    fp:     '>=0.4.2 <0.5.0'
    di:     '^3.3.7'

